/*
 * AhaSend Email API
 * This is the API documentation for sending emails via [AhaSend.com](https://ahasend.com). To use this API you need to get your API Key from your account under the API Keys page.
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@ahasend.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ahasend.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * SuccessfulResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-04-15T06:03:59.323628806Z[GMT]")

public class SuccessfulResponse {
  @JsonProperty("success_count")
  private Integer successCount = null;

  @JsonProperty("fail_count")
  private Integer failCount = null;

  @JsonProperty("failed_recipients")
  private List<String> failedRecipients = null;

  @JsonProperty("errors")
  private List<String> errors = null;

  public SuccessfulResponse successCount(Integer successCount) {
    this.successCount = successCount;
    return this;
  }

   /**
   * Number of messages that were queued for sending.
   * @return successCount
  **/
  @Schema(example = "1", description = "Number of messages that were queued for sending.")
  public Integer getSuccessCount() {
    return successCount;
  }

  public void setSuccessCount(Integer successCount) {
    this.successCount = successCount;
  }

  public SuccessfulResponse failCount(Integer failCount) {
    this.failCount = failCount;
    return this;
  }

   /**
   * Number of messages that failed to be queued for sending.
   * @return failCount
  **/
  @Schema(example = "1", description = "Number of messages that failed to be queued for sending.")
  public Integer getFailCount() {
    return failCount;
  }

  public void setFailCount(Integer failCount) {
    this.failCount = failCount;
  }

  public SuccessfulResponse failedRecipients(List<String> failedRecipients) {
    this.failedRecipients = failedRecipients;
    return this;
  }

  public SuccessfulResponse addFailedRecipientsItem(String failedRecipientsItem) {
    if (this.failedRecipients == null) {
      this.failedRecipients = new ArrayList<String>();
    }
    this.failedRecipients.add(failedRecipientsItem);
    return this;
  }

   /**
   * List of email addresses that the email was not sent to.
   * @return failedRecipients
  **/
  @Schema(example = "[\"john@nasa.gov\"]", description = "List of email addresses that the email was not sent to.")
  public List<String> getFailedRecipients() {
    return failedRecipients;
  }

  public void setFailedRecipients(List<String> failedRecipients) {
    this.failedRecipients = failedRecipients;
  }

  public SuccessfulResponse errors(List<String> errors) {
    this.errors = errors;
    return this;
  }

  public SuccessfulResponse addErrorsItem(String errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<String>();
    }
    this.errors.add(errorsItem);
    return this;
  }

   /**
   * Get errors
   * @return errors
  **/
  @Schema(example = "[\"john@nasa.gov: The email account that you tried to reach does not exist.\"]", description = "")
  public List<String> getErrors() {
    return errors;
  }

  public void setErrors(List<String> errors) {
    this.errors = errors;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SuccessfulResponse successfulResponse = (SuccessfulResponse) o;
    return Objects.equals(this.successCount, successfulResponse.successCount) &&
        Objects.equals(this.failCount, successfulResponse.failCount) &&
        Objects.equals(this.failedRecipients, successfulResponse.failedRecipients) &&
        Objects.equals(this.errors, successfulResponse.errors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(successCount, failCount, failedRecipients, errors);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SuccessfulResponse {\n");
    
    sb.append("    successCount: ").append(toIndentedString(successCount)).append("\n");
    sb.append("    failCount: ").append(toIndentedString(failCount)).append("\n");
    sb.append("    failedRecipients: ").append(toIndentedString(failedRecipients)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
